config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/about'
  get 'pages/projects'
  get 'pages/contact'
  get "/pages/:page" => "pages#show"

  root "pages#home"

  resources :pages

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def home
  end

  def help
  end

  def about
end

  def contact
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def projects
  end

  def contact
  end
end

app/controllers/project1_controller.rb
class Project1Controller < ApplicationController
  def show
  UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project1_helper.rb
module Project1Helper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Resume</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
    <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
    .w3-bar-block .w3-bar-item {padding:20px}
    </style>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="pages/home">Ben S</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="root_path">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/contact">Contact</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Projects
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Project 1</a>
              <a class="dropdown-item" href="#">Project 2</a>
              <a class="dropdown-item" href="#">Project 3</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>




  <%= yield %>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/_blog.html.erb
<div class="row">
  <div class="leftcolumn">
    <div class="card">
      <h2>TITLE HEADING</h2>
      <h5>Title description, Dec 7, 2017</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Some text..</p>
      <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    </div>
    <div class="card">
      <h2>TITLE HEADING</h2>
      <h5>Title description, Sep 2, 2017</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Some text..</p>
      <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    </div>
  </div>
</div>

app/views/pages/_header.html.erb
<nav>
      <ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "About",   pages_about_path %></li>
          <li><%= link_to "Contact", pages_contact_path %></li>
       </ul>
  </nav>

app/views/pages/about.html.erb
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">


  <main role="main">

        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
          <div class="container">
            <h1 class="display-3">Hello, world!</h1>
            <p>This is my portfolio website. It includes content which demonstrates skills I aquired during my full stack school. Please check out links for more information.</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
          </div>
        </div>

        <div class="container">
          <!-- Example row of columns -->
          <div class="row">
            <div class="col-md-4">
              <h2>Github</h2>
              <p>This will take you to my GitHub which contains projects I completed for school and projects I've completed. </p>
              <p><a class="btn btn-secondary" href="#" role="button">GitHub »</a></p>
            </div>
            <div class="col-md-4">
              <h2>LinkdIn</h2>
              <p>Linked in click it </p>
              <p><a class="btn btn-secondary" href="#" role="button">LinkedIn »</a></p>
            </div>
            <div class="col-md-4">
              <h2>Upwork</h2>
              <p>Hire me</p>
              <p><a class="btn btn-secondary" href="#" role="button">Upwork »</a></p>
            </div>
          </div>

          <hr>

        </div> <!-- /container -->

      </main>

app/views/pages/contact.html.erb
<div>
      <form action="" class="contact" onsubmit="return false;">
     <fieldset class="contact-inner">
      <p class="contact-input">
      <input type="text" name="name" placeholder="Your Name…" autofocus>
      </p>

    <p class="contact-input">
      <label for="select" class="select">
        <select name="subject" id="select">
          <option value="" selected>Choose Subject…</option>
          <option value="1">Schedule Appointment</option>
          <option value="1">Get more info</option>
          <option value="1">Other</option>
        </select>
      </label>
    </p>

    <p class="contact-input">
      <textarea name="message" placeholder="Your Message…"></textarea>
    </p>

    <p class="contact-submit">
      <input type="submit" value="Send Message">
    </p>
  </fieldset>
</form>

    </div>

app/views/pages/home.html.erb
    <div class="container">
    	<div class="row">
    		<div class="col-lg-12">
    			<div id="content">
    				<h1>Full Stack </br> Portfolio</h1>
    				<h3>Leggings venmo asymmetrical irony lyft.<br /><br /> Banh mi mustache food truck waistcoat williamsburg.<br /> Beard pork belly pour-over twee,<br />slow-carb cray quinoa scenester fam iPhone pitchfork.</h3>
    				<hr />
    				<button class="btn btn-default btn-lg"><i class="fa fa-cloud-download" aria-hidden="true"></i> Download Now</button>
    			</div>
    		</div>
    	</div>
    </div>

app/views/pages/projects.html.erb
<h1>Pages#projects</h1>
<p>Find me in app/views/pages/projects.html.erb</p>